/*

 BAT_SPR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 11

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bat_spr_h_INCLUDE
#define __bat_spr_h_INCLUDE

/* Bank of tiles. */
#define batSprBank 0
/* Start of tile array. */
extern const unsigned char batSpr[];

#endif

/* End of BAT_SPR.H */
