/*

 SCORE0_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 8
   Tile set      : C:\Users\Birk\Documents\GitHub\Pong-Battle\res\score_spr.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __score0_map_h_INCLUDE
#define __score0_map_h_INCLUDE

#define score0MapWidth 5
#define score0MapHeight 8
#define score0MapBank 0

extern const unsigned char score0Map[];

#endif

/* End of SCORE0_MAP.H */
