/*

 SCORE2_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 8
   Tile set      : C:\Users\Birk\Documents\GitHub\Pong-Battle\res\score_spr.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __score2_map_h_INCLUDE
#define __score2_map_h_INCLUDE

#define score2MapWidth 5
#define score2MapHeight 8
#define score2MapBank 0

extern const unsigned char score2Map[];

#endif

/* End of SCORE2_MAP.H */
