/*

 SCORE1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 8
   Tile set      : C:\Users\Birk\Documents\GitHub\Pong-Battle\res\score_spr.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __score1_map_h_INCLUDE
#define __score1_map_h_INCLUDE

#define score1MapWidth 5
#define score1MapHeight 8
#define score1MapBank 0

extern const unsigned char score1Map[];

#endif

/* End of SCORE1_MAP.H */
