/*

 SCORE3_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 8
   Tile set      : C:\Users\Birk\Documents\GitHub\Pong-Battle\res\score_spr.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __score3_map_h_INCLUDE
#define __score3_map_h_INCLUDE

#define score3MapWidth 5
#define score3MapHeight 8
#define score3MapBank 0

extern const unsigned char score3Map[];

#endif

/* End of SCORE3_MAP.H */
